name: evm-vm-tests
on:
  push:
    branches: [master, develop]
    tags: ['*']

env:
  cwd: ${{github.workspace}}/packages/evm-vm-tests

defaults:
  run:
    working-directory: packages/evm-vm-tests

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-vm-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
        working-directory: ${{github.workspace}}

      - run: npm run test:state:selectedForks

  test-vm-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
        working-directory: ${{github.workspace}}

      - run: npm run test:blockchain
