name: VM Nightly
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

env:
  cwd: ${{github.workspace}}/packages/vm

defaults:
  run:
    working-directory: packages/vm

jobs:
  test-vm-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      # The job is meant to run with a fresh lock file
      # to detect any possible issues with new dep versions.
      - run: rm package-lock.json
        working-directory: ${{github.workspace}}

      - run: npm i
        working-directory: ${{github.workspace}}

      - run: npm run test:API
      - run: npm run test:API:browser

  evm-vm-tests-state:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      # The job is meant to run with a fresh lock file
      # to detect any possible issues with new dep versions.
      - run: rm package-lock.json
        working-directory: ${{github.workspace}}

      - run: npm i
        working-directory: ${{github.workspace}}

      - run: npm run test:state:allForks
        working-directory: ${{github.workspace}}/packages/evm-vm-tests


  test-vm-blockchain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      # The job is meant to run with a fresh lock file
      # to detect any possible issues with new dep versions.
      - run: rm package-lock.json
        working-directory: ${{github.workspace}}

      - run: npm i
        working-directory: ${{github.workspace}}

      - run: npm run test:blockchain:allForks
        working-directory: ${{github.workspace}}/packages/evm-vm-tests

  evm-vm-tests-slow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      # The job is meant to run with a fresh lock file
      # to detect any possible issues with new dep versions.
      - run: rm package-lock.json
        working-directory: ${{github.workspace}}

      - run: npm i
        working-directory: ${{github.workspace}}

      - run: npm run test:state:slow
        working-directory: ${{github.workspace}}/packages/evm-vm-tests
